AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - Rakefile
    - spec/rails_helper.rb

Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - smoketest
    - prod

Rails/UniqBeforePluck:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: trueA
  Max: 10

Naming/PredicateName:
  Enabled: false

RescueModifier:
  Enabled: false

RescueStandardError:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  Enabled: false
